### ISSUE TITLE
Rendering / Building Server Side app following instructions in DNC #34

### ISSUE THREAD

**Issue by ultrarunner** [dotnetcurry/angular-universal-app#1]
First of all, thank you very much for the tutorial on rendering server side app in Angular. Following the instructions in DNC #34 (https://dncmagazine.blob.core.windows.net/edition34/DNCMag-Issue34.pdf) using docker containers, I got stuck trying to render the server side app running the "npm run serve:ssr". It seems like there is a path issue related to pointing to the "dist-server" instead of "dist" as well as a "browser" subfolder that does not seem to be built at run-time within the "dist" folder. I forked the repo and fixed those issues locally. Let me know if I need to create a pull request for this. 
https://github.com/ultrarunner/angular-universal-app/commit/84dcb969de7c438126d9dd60d2c245219790a2a8
Also, I am new to contributing to github. Please let me know if I can improve on submitting issues, help fixing code or the overall process. Thank you again for the great articles.

**Comment by Gajendrasinh** [comment]
How to deployed final build folder on server,

i have uploaded build folder without node_modules but its not working, if i am add node_module then its working fine, i am using nginx server

**Comment by haripulaparthi** [comment]
Hi , I am also facing the same issue as @ultrarunner . Please let me know if we have work around for this issue.
